apiVersion: v1
kind: Service
metadata:
  name: flask-hello-world
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8080
    nodePort: {{ .Values.service.nodePort }}
  selector:
    app: flask-hello-world
